

name: Create release of the app

on:
  push:
    tags: ['v*'] # Push events to matching v*, i.e. v1.0, v20.15.10
    branches: [ master ]
    
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Build Release APK
      run: ./gradlew assembleRelease  
      
    - name: Releasing using Hub And 
      uses: ShowMeThe/github_action_release@master
      # ID used to access action output
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release/app-release-unsigned.apk
#       signingKeyBase64: ${{ secrets.SIGNING_KEY }}
#       alias: ${{ secrets.ALIAS }}
#       keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
#       keyPassword: ${{ secrets.KEY_PASSWORD }}
      
  # Example use of `signedReleaseFile` output -- not needed
    - uses: actions/upload-artifact@v2
      with:
        name: Signed app bundle
        path: ${{steps.sign_app.releaseDirectory}}